### PR TITLE
Dart NNBD migration(null-safety)

### PR DESCRIPTION
**Pull request by HrBDev**
Initial migration to dart null-safety for a beta(.nullsafety) version until all dependencies(shimmer) release stable null safe versions

### CODE REVIEW

**Comment by M123-dev** [comment]
@HrBDev shimmer now has a null-safety preview. [Here](https://pub.dev/packages/shimmer/versions/2.0.0-nullsafety.0)

**Comment by micaelcid** [comment]
Hey, @HrBDev are you going to keep working on these changes?

It'd be great to have this package migrated to null-safety!

**Comment by micaelcid** [comment]
What do you think @lhamycodes?

**Comment by lhamycodes** [comment]
Thanks all. I was unavailable for a while but I've migrated the package to support null-safety.

**Pull request closed without merging**
